### PR TITLE
Using inferno logo as demo animation + Optimizations

### PR DESCRIPTION
**Pull request by farooqkz**
This PR... 
 - Adds appropriate JSX flags whenever possible in the demo animation
 - Uses Inferno logo as the blocks of the demo animation on the main page
 
However CSS properties of `animate-grid` must get changed to have the blocks(pixels) close to each other instead of being far way from each other. Tell me what to add and the PR will be ready as soon as possible.

### CODE REVIEW

**Comment by jhsware** [comment]
@farooqkz Could you attach a screenshot of what this would look like? I can't access the Vercel preview.

I put a lot of effort into maintaining the minimalistic design of the site in the demo and I would like to confirm that this is a visual improvement.

**Comment by farooqkz** [comment]
I'll send a small recording as soon as possible. I just made your demo animation use a 16x16 version of Inferno logo.

**Comment by farooqkz** [comment]
Just did `yarn install` and `yarn run dev` but `localhost:8082` is just a single line of text:
```
ReferenceError: Image is not defined
```

**Comment by Havunen** [comment]
> Just did `yarn install` and `yarn run dev` but `localhost:8082` is just a single line of text:
> 
> ```
> ReferenceError: Image is not defined
> ```

I think its because of the code you added: https://github.com/infernojs/inferno-website/pull/162/files#diff-29c13ff38598d899019fec18e2b6d1f2e4c4c2e994f52d18f7250eb369a3f633R12
it also runs on server so I guess nodejs does not have any meaning for "Image"

**Comment by jhsware** [comment]
Now I think I get what you want to do. Correct me if I am wrong but you want to create a mosaic of the logo and animate the different tiles?

I don't think the demo slot on the frontpage will be the right place for such an animation, it will either be a bit small or push the rest of the content below the fold on smaller screens.

What we could do instead is create a really cool demo based on this idea as a separate page and link that from the demo. On this page we could create a mosaic of the logo and create some super cool effects using animations on appear, move and disappear. This would also allow us to stress test the animation code if we have user selectable size of the mosaic.

**Comment by farooqkz** [comment]
> Now I think I get what you want to do. Correct me if I am wrong but you want to create a mosaic of the logo and animate the different tiles?
> 
> I don't think the demo slot on the frontpage will be the right place for such an animation, it will either be a bit small or push the rest of the content below the fold on smaller screens.
> 
> What we could do instead is create a really cool demo based on this idea as a separate page and link that from the demo. On this page we could create a mosaic of the logo and create some super cool effects using animations on appear, move and disappear. This would also allow us to stress test the animation code if we have user selectable size of the mosaic.

Yes that's exactly what I have in my mind. And a separate demo page sounds good to me.

**Comment by farooqkz** [comment]
So what to do about this?

**Comment by Havunen** [comment]
Lets close this issue, the logo is fine IMO.

**Pull request closed without merging**
