### PR TITLE
Changed Routing example to work with SSR and to use new import() code splitting syntax

### PR DESCRIPTION
**Pull request by conblem**
[https://webpack.js.org/guides/code-splitting-async/](https://webpack.js.org/guides/code-splitting-async/)
`webpack supports two similar techniques to achieve this goal: using import() (preferred, ECMAScript proposal) and require.ensure() (legacy, webpack specific).`
We should use the import() syntax as require.ensure() is already legacy

### CODE REVIEW

**Comment by LukeSheard** [comment]
It would be good to add a note that `import()`syntax isn't currently in Typescript (see Microsoft/Typescript#14495).

**Comment by conblem** [comment]
@LukeSheard i just read through the issue and will add a commit, thanks for the info.

**Comment by conblem** [comment]
@LukeSheard could you take a look at my PR again.

**Comment by LukeSheard** [comment]
Looks good to me!

**Pull request merged**
